// Ubicaciones del Perú: Departamento -> Provincia -> Distritos
// Cobertura completa de provincias por departamento. Los distritos se
// incluyen para las provincias principales; para las demás, el cliente
// puede escribir el distrito libremente (campo con opción "Otro").

export type Ubigeo = Record<string, Record<string, string[]>>;

export const PERU: Ubigeo = {
  Amazonas: {
    Chachapoyas: ["Chachapoyas", "Huancas", "La Jalca", "Levanto", "Molinopampa"],
    Bagua: ["Bagua", "Aramango", "Copallín", "El Parco", "Imaza"],
    Bongará: ["Jumbilla", "Chisquilla", "Corosha"],
    Condorcanqui: ["Nieva", "El Cenepa", "Río Santiago"],
    "Luya": ["Lamud", "Camporredondo", "Cocabamba"],
    "Rodríguez de Mendoza": ["San Nicolás", "Chirimoto", "Cochamal"],
    Utcubamba: ["Bagua Grande", "Cajaruro", "Cumba", "Lonya Grande"],
  },
  "Áncash": {
    Huaraz: ["Huaraz", "Independencia", "Cochabamba", "Jangas", "Tarica"],
    Aija: ["Aija", "Coris", "La Merced"],
    "Antonio Raymondi": ["Llamellín", "Aczo", "Chaccho"],
    Asunción: ["Chacas", "Acochaca"],
    Bolognesi: ["Chiquián", "Aquia", "Cajacay"],
    Carhuaz: ["Carhuaz", "Acopampa", "Amashca"],
    "Carlos Fermín Fitzcarrald": ["San Luis", "San Nicolás", "Yauya"],
    Casma: ["Casma", "Buena Vista Alta", "Comandante Noel", "Yaután"],
    Corongo: ["Corongo", "Aco", "Bambas"],
    Huari: ["Huari", "Anra", "Cajay", "Chavín de Huántar"],
    Huarmey: ["Huarmey", "Cochapetí", "Culebras", "Huayán"],
    Huaylas: ["Caraz", "Huallanca", "Huata", "Mato"],
    "Mariscal Luzuriaga": ["Piscobamba", "Casca", "Lucma"],
    Ocros: ["Ocros", "Acas", "Cajamarquilla"],
    Pallasca: ["Cabana", "Bolognesi", "Conchucos"],
    Pomabamba: ["Pomabamba", "Huayllán", "Parobamba"],
    Recuay: ["Recuay", "Catac", "Cotaparaco"],
    Santa: ["Chimbote", "Nuevo Chimbote", "Coishco", "Nepeña", "Samanco", "Santa"],
    Sihuas: ["Sihuas", "Acobamba", "Alfonso Ugarte"],
    Yungay: ["Yungay", "Cascapara", "Mancos", "Ranrahirca"],
  },
  "Apurímac": {
    Abancay: ["Abancay", "Chacoche", "Circa", "Curahuasi", "Tamburco"],
    Andahuaylas: ["Andahuaylas", "Andarapa", "Chiara", "Talavera"],
    Antabamba: ["Antabamba", "El Oro", "Huaquirca"],
    Aymaraes: ["Chalhuanca", "Capaya", "Caraybamba"],
    Cotabambas: ["Tambobamba", "Cotabambas", "Coyllurqui"],
    Chincheros: ["Chincheros", "Anco-Huallo", "Cocharcas"],
    Grau: ["Chuquibambilla", "Curpahuasi", "Gamarra"],
  },
  Arequipa: {
    Arequipa: ["Arequipa", "Cayma", "Cerro Colorado", "Characato", "José Luis Bustamante y Rivero", "Mariano Melgar", "Miraflores", "Paucarpata", "Sachaca", "Socabaya", "Yanahuara", "Alto Selva Alegre", "Hunter"],
    Camaná: ["Camaná", "José María Quimper", "Mariano Nicolás Valcárcel", "Samuel Pastor"],
    Caravelí: ["Caravelí", "Acarí", "Atico", "Chala"],
    Castilla: ["Aplao", "Andagua", "Chachas"],
    Caylloma: ["Chivay", "Cabanaconde", "Majes", "Yura"],
    Condesuyos: ["Chuquibamba", "Andaray", "Cayarani"],
    Islay: ["Mollendo", "Cocachacra", "Dean Valdivia", "Islay", "Mejía"],
    "La Unión": ["Cotahuasi", "Alca", "Charcana"],
  },
  Ayacucho: {
    Huamanga: ["Ayacucho", "Carmen Alto", "Jesús Nazareno", "San Juan Bautista", "Andrés Avelino Cáceres Dorregaray"],
    Cangallo: ["Cangallo", "Chuschi", "Los Morochucos"],
    "Huanca Sancos": ["Sancos", "Carapo", "Sacsamarca"],
    Huanta: ["Huanta", "Ayahuanco", "Huamanguilla", "Luricocha"],
    "La Mar": ["San Miguel", "Anco", "Ayna", "Chungui"],
    Lucanas: ["Puquio", "Aucará", "Cabana"],
    Parinacochas: ["Coracora", "Chumpi", "Coronel Castañeda"],
    "Páucar del Sara Sara": ["Pausa", "Colta", "Corculla"],
    Sucre: ["Querobamba", "Belén", "Chalcos"],
    "Víctor Fajardo": ["Huancapi", "Alcamenca", "Apongo"],
    Vilcashuamán: ["Vilcashuamán", "Accomarca", "Carhuanca"],
  },
  Cajamarca: {
    Cajamarca: ["Cajamarca", "Baños del Inca", "Jesús", "Llacanora", "Los Baños del Inca"],
    Cajabamba: ["Cajabamba", "Cachachi", "Condebamba"],
    Celendín: ["Celendín", "Chumuch", "Cortegana"],
    Chota: ["Chota", "Anguía", "Chadín", "Lajas"],
    Contumazá: ["Contumazá", "Chilete", "Cupisnique"],
    Cutervo: ["Cutervo", "Callayuc", "Choros"],
    Hualgayoc: ["Bambamarca", "Chugur", "Hualgayoc"],
    Jaén: ["Jaén", "Bellavista", "Colasay", "Pomahuaca"],
    "San Ignacio": ["San Ignacio", "Chirinos", "Huarango"],
    "San Marcos": ["Pedro Gálvez", "Chancay", "Eduardo Villanueva"],
    "San Miguel": ["San Miguel", "Bolívar", "Calquis"],
    "San Pablo": ["San Pablo", "San Bernardino", "San Luis"],
    "Santa Cruz": ["Santa Cruz", "Andabamba", "Catache"],
  },
  Callao: {
    "Prov. Const. del Callao": ["Callao", "Bellavista", "Carmen de la Legua Reynoso", "La Perla", "La Punta", "Ventanilla", "Mi Perú"],
  },
  Cusco: {
    Cusco: ["Cusco", "San Jerónimo", "San Sebastián", "Santiago", "Wanchaq", "Saylla", "Poroy"],
    Acomayo: ["Acomayo", "Acopia", "Acos"],
    Anta: ["Anta", "Ancahuasi", "Cachimayo", "Zurite"],
    Calca: ["Calca", "Coya", "Lamay", "Pisac"],
    Canas: ["Yanaoca", "Checca", "Kunturkanki"],
    Canchis: ["Sicuani", "Checacupe", "Combapata", "Tinta"],
    Chumbivilcas: ["Santo Tomás", "Capacmarca", "Chamaca"],
    Espinar: ["Espinar", "Condoroma", "Coporaque"],
    "La Convención": ["Santa Ana", "Echarate", "Maranura", "Quellouno"],
    Paruro: ["Paruro", "Accha", "Ccapi"],
    Paucartambo: ["Paucartambo", "Caicay", "Challabamba"],
    Quispicanchi: ["Urcos", "Andahuaylillas", "Ccatca", "Oropesa"],
    Urubamba: ["Urubamba", "Chinchero", "Machupicchu", "Ollantaytambo", "Yucay"],
  },
  Huancavelica: {
    Huancavelica: ["Huancavelica", "Acobambilla", "Ascensión", "Yauli"],
    Acobamba: ["Acobamba", "Andabamba", "Anta"],
    Angaraes: ["Lircay", "Anchonga", "Callanmarca"],
    Castrovirreyna: ["Castrovirreyna", "Arma", "Aurahua"],
    Churcampa: ["Churcampa", "Anco", "Chinchihuasi"],
    Huaytará: ["Huaytará", "Ayaví", "Córdova"],
    Tayacaja: ["Pampas", "Acostambo", "Colcabamba", "Daniel Hernández"],
  },
  "Huánuco": {
    Huánuco: ["Huánuco", "Amarilis", "Pillco Marca", "Santa María del Valle", "Chinchao"],
    Ambo: ["Ambo", "Cayna", "Colpas"],
    "Dos de Mayo": ["La Unión", "Chuquis", "Marías"],
    Huacaybamba: ["Huacaybamba", "Canchabamba", "Cochabamba"],
    Huamalíes: ["Llata", "Arancay", "Chavín de Pariarca"],
    "Leoncio Prado": ["Rupa-Rupa", "Daniel Alomía Robles", "José Crespo y Castillo"],
    Marañón: ["Huacrachuco", "Cholón", "San Buenaventura"],
    Pachitea: ["Panao", "Chaglla", "Molino"],
    "Puerto Inca": ["Puerto Inca", "Codo del Pozuzo", "Honoria"],
    Lauricocha: ["Jesús", "Baños", "Jivia"],
    Yarowilca: ["Chavinillo", "Cahuac", "Chacabamba"],
  },
  Ica: {
    Ica: ["Ica", "La Tinguiña", "Los Aquijes", "Parcona", "Salas", "Subtanjalla", "San Juan Bautista"],
    Chincha: ["Chincha Alta", "Chincha Baja", "El Carmen", "Grocio Prado", "Pueblo Nuevo", "Sunampe"],
    Nasca: ["Nasca", "Changuillo", "El Ingenio", "Marcona", "Vista Alegre"],
    Palpa: ["Palpa", "Llipata", "Río Grande"],
    Pisco: ["Pisco", "Humay", "Independencia", "Paracas", "San Andrés", "San Clemente", "Túpac Amaru Inca"],
  },
  "Junín": {
    Huancayo: ["Huancayo", "Chilca", "El Tambo", "Pilcomayo", "San Agustín", "Sapallanga", "Sicaya"],
    Concepción: ["Concepción", "Aco", "Andamarca", "Manzanares"],
    Chanchamayo: ["La Merced", "Perené", "Pichanaqui", "San Luis de Shuaro", "San Ramón"],
    Jauja: ["Jauja", "Acolla", "Apata", "Yauyos"],
    Junín: ["Junín", "Carhuamayo", "Ondores", "Ulcumayo"],
    Satipo: ["Satipo", "Coviriali", "Llaylla", "Mazamari", "Pangoa", "Río Negro", "Río Tambo"],
    Tarma: ["Tarma", "Acobamba", "Huaricolca", "Palca", "San Pedro de Cajas"],
    "Yauli": ["La Oroya", "Chacapalpa", "Huay-Huay", "Morococha", "Santa Rosa de Sacco"],
    Chupaca: ["Chupaca", "Ahuac", "Chongos Bajo", "Huamancaca Chico"],
  },
  "La Libertad": {
    Trujillo: ["Trujillo", "El Porvenir", "Florencia de Mora", "Huanchaco", "La Esperanza", "Laredo", "Moche", "Salaverry", "Víctor Larco Herrera"],
    Ascope: ["Ascope", "Chicama", "Chocope", "Paiján", "Rázuri", "Casa Grande"],
    "Bolívar": ["Bolívar", "Bambamarca", "Condormarca"],
    Chepén: ["Chepén", "Pacanga", "Pueblo Nuevo"],
    Julcán: ["Julcán", "Calamarca", "Carabamba"],
    Otuzco: ["Otuzco", "Agallpampa", "Charat", "Salpo"],
    Pacasmayo: ["San Pedro de Lloc", "Guadalupe", "Jequetepeque", "Pacasmayo", "San José"],
    Pataz: ["Tayabamba", "Buldibuyo", "Chillia", "Huaylillas"],
    "Sánchez Carrión": ["Huamachuco", "Chugay", "Cochorco", "Curgos"],
    "Santiago de Chuco": ["Santiago de Chuco", "Angasmarca", "Cachicadán"],
    "Gran Chimú": ["Cascas", "Lucma", "Marmot", "Sayapullo"],
    Virú: ["Virú", "Chao", "Guadalupito"],
  },
  Lambayeque: {
    Chiclayo: ["Chiclayo", "José Leonardo Ortiz", "La Victoria", "Monsefú", "Pimentel", "Reque", "Santa Rosa", "Pomalca", "Tumán"],
    Ferreñafe: ["Ferreñafe", "Cañaris", "Incahuasi", "Pítipo", "Pueblo Nuevo"],
    Lambayeque: ["Lambayeque", "Illimo", "Jayanca", "Mochumí", "Mórrope", "Motupe", "Olmos", "Túcume", "San José"],
  },
  Lima: {
    Lima: ["Lima (Cercado)", "Ate", "Barranco", "Breña", "Carabayllo", "Chaclacayo", "Chorrillos", "Cieneguilla", "Comas", "El Agustino", "Independencia", "Jesús María", "La Molina", "La Victoria", "Lince", "Los Olivos", "Lurigancho (Chosica)", "Lurín", "Magdalena del Mar", "Miraflores", "Pachacámac", "Pueblo Libre", "Puente Piedra", "Rímac", "San Borja", "San Isidro", "San Juan de Lurigancho", "San Juan de Miraflores", "San Luis", "San Martín de Porres", "San Miguel", "Santa Anita", "Santiago de Surco", "Surquillo", "Villa El Salvador", "Villa María del Triunfo"],
    Barranca: ["Barranca", "Paramonga", "Pativilca", "Supe", "Supe Puerto"],
    Cajatambo: ["Cajatambo", "Copa", "Gorgor"],
    Canta: ["Canta", "Arahuay", "Huamantanga"],
    Cañete: ["San Vicente de Cañete", "Asia", "Cerro Azul", "Imperial", "Mala", "Nuevo Imperial", "Quilmaná", "San Antonio"],
    Huaral: ["Huaral", "Aucallama", "Chancay", "Ihuari"],
    Huarochirí: ["Matucana", "Ricardo Palma", "San Mateo", "Santa Eulalia"],
    Huaura: ["Huacho", "Ámbar", "Caleta de Carquín", "Hualmay", "Santa María", "Sayán", "Végueta"],
    Oyón: ["Oyón", "Andajes", "Caujul"],
    Yauyos: ["Yauyos", "Alis", "Ayauca"],
  },
  Loreto: {
    Maynas: ["Iquitos", "Belén", "Punchana", "San Juan Bautista", "Fernando Lores"],
    "Alto Amazonas": ["Yurimaguas", "Balsapuerto", "Jeberos"],
    Loreto: ["Nauta", "Parinari", "Tigre", "Trompeteros"],
    "Mariscal Ramón Castilla": ["Ramón Castilla", "Pebas", "Yavarí"],
    Requena: ["Requena", "Alto Tapiche", "Capelo"],
    Ucayali: ["Contamana", "Inahuaya", "Padre Márquez"],
    "Datem del Marañón": ["Barranca", "Cahuapanas", "Manseriche"],
    Putumayo: ["Putumayo", "Rosa Panduro", "Teniente Manuel Clavero"],
  },
  "Madre de Dios": {
    Tambopata: ["Tambopata", "Inambari", "Las Piedras", "Laberinto"],
    Manu: ["Manu", "Fitzcarrald", "Madre de Dios", "Huepetuhe"],
    Tahuamanu: ["Iñapari", "Iberia", "Tahuamanu"],
  },
  Moquegua: {
    "Mariscal Nieto": ["Moquegua", "Carumas", "Cuchumbaya", "Samegua", "Torata"],
    "General Sánchez Cerro": ["Omate", "Chojata", "Coalaque"],
    Ilo: ["Ilo", "El Algarrobal", "Pacocha"],
  },
  Pasco: {
    Pasco: ["Chaupimarca", "Yanacancha", "Simón Bolívar", "Tinyahuarco"],
    "Daniel Alcides Carrión": ["Yanahuanca", "Chacayán", "Goyllarisquizga"],
    Oxapampa: ["Oxapampa", "Chontabamba", "Huancabamba", "Pozuzo", "Villa Rica"],
  },
  Piura: {
    Piura: ["Piura", "Castilla", "Catacaos", "Cura Mori", "La Arena", "La Unión", "Las Lomas", "Tambo Grande", "Veintiséis de Octubre"],
    Ayabaca: ["Ayabaca", "Frías", "Jililí", "Montero"],
    Huancabamba: ["Huancabamba", "Canchaque", "El Carmen de la Frontera"],
    Morropón: ["Chulucanas", "Buenos Aires", "Chalaco", "Morropón"],
    Paita: ["Paita", "Amotape", "Colán", "La Huaca"],
    Sullana: ["Sullana", "Bellavista", "Ignacio Escudero", "Marcavelica", "Querecotillo"],
    Talara: ["Pariñas", "El Alto", "La Brea", "Lobitos", "Los Órganos", "Máncora"],
    Sechura: ["Sechura", "Bellavista de la Unión", "Bernal", "Vice"],
  },
  Puno: {
    Puno: ["Puno", "Acora", "Amantani", "Atuncolla", "Chucuito", "Paucarcolla"],
    Azángaro: ["Azángaro", "Achaya", "Arapa", "Asillo"],
    Carabaya: ["Macusani", "Ajoyani", "Ayapata"],
    Chucuito: ["Juli", "Desaguadero", "Huacullani", "Pomata", "Zepita"],
    "El Collao": ["Ilave", "Capazo", "Pilcuyo", "Santa Rosa"],
    Huancané: ["Huancané", "Cojata", "Huatasani"],
    Lampa: ["Lampa", "Cabanilla", "Calapuja"],
    Melgar: ["Ayaviri", "Antauta", "Cupi", "Llalli"],
    Moho: ["Moho", "Conima", "Huayrapata"],
    "San Antonio de Putina": ["Putina", "Ananea", "Pedro Vilca Apaza"],
    "San Román": ["Juliaca", "Cabana", "Cabanillas", "Caracoto"],
    Sandia: ["Sandia", "Cuyocuyo", "Limbani", "Patambuco"],
    Yunguyo: ["Yunguyo", "Anapia", "Copani", "Cuturapi"],
  },
  "San Martín": {
    Moyobamba: ["Moyobamba", "Calzada", "Habana", "Jepelacio", "Soritor"],
    Bellavista: ["Bellavista", "Alto Biavo", "Bajo Biavo", "San Pablo"],
    "El Dorado": ["San José de Sisa", "Agua Blanca", "San Martín"],
    Huallaga: ["Saposoa", "Alto Saposoa", "El Eslabón"],
    Lamas: ["Lamas", "Alonso de Alvarado", "Barranquita", "Caynarachi"],
    "Mariscal Cáceres": ["Juanjuí", "Campanilla", "Huicungo", "Pachiza"],
    Picota: ["Picota", "Buenos Aires", "Caspisapa", "Pilluana"],
    Rioja: ["Rioja", "Awajún", "Elías Soplín Vargas", "Nueva Cajamarca"],
    "San Martín": ["Tarapoto", "Alberto Leveau", "Cacatachi", "Juan Guerra", "La Banda de Shilcayo", "Morales"],
    Tocache: ["Tocache", "Nuevo Progreso", "Pólvora", "Shunte", "Uchiza"],
  },
  Tacna: {
    Tacna: ["Tacna", "Alto de la Alianza", "Calana", "Ciudad Nueva", "Pocollay", "Coronel Gregorio Albarracín Lanchipa"],
    Candarave: ["Candarave", "Cairani", "Camilaca"],
    "Jorge Basadre": ["Locumba", "Ilabaya", "Ite"],
    Tarata: ["Tarata", "Héroes Albarracín", "Estique"],
  },
  Tumbes: {
    Tumbes: ["Tumbes", "Corrales", "La Cruz", "Pampas de Hospital", "San Jacinto", "San Juan de la Virgen"],
    "Contralmirante Villar": ["Zorritos", "Casitas", "Canoas de Punta Sal"],
    Zarumilla: ["Zarumilla", "Aguas Verdes", "Matapalo", "Papayal"],
  },
  Ucayali: {
    "Coronel Portillo": ["Callería", "Campoverde", "Manantay", "Yarinacocha", "Nueva Requena"],
    "Atalaya": ["Raymondi", "Sepahua", "Tahuania", "Yurúa"],
    "Padre Abad": ["Padre Abad", "Curimaná", "Irazola", "Neshuya"],
    Purús: ["Purús"],
  },
};

export const DEPARTAMENTOS = Object.keys(PERU);

export function getProvincias(dep: string): string[] {
  return PERU[dep] ? Object.keys(PERU[dep]) : [];
}

export function getDistritos(dep: string, prov: string): string[] {
  return PERU[dep]?.[prov] || [];
}
